import time
print('открыть захват')
time.sleep(2)
print('закрыть захват')
time.sleep(1)
print('поворот ввлево')
time.sleep(1)
print('открыть захват')
time.sleep(1)
print('спуск ввниз')
time.sleep(1)
print('открыть захват')
time.sleep(1)
print('закрыть захват')
time.sleep(1)
print('поднятся')
time.sleep(1)
print('поворот ввылево')
time.sleep(1)
print('открыть захват')
time.sleep(1)
